#!/usr/bin/env bash
set -euo pipefail

ids=$(grep -h '^- id: ' "$PROJECT_ROOT"/governance/*.yaml | sed 's/^- id: //')
enumeration=$(printf '%s\n' "$ids" | sed 's/["\\]/\\&/g; s/.*/"&"/' | paste -sd, -)
alternation=$(printf '%s\n' "$ids" | sed 's/[][\\.^$*+?(){}|]/\\&/g; s/\\/\\\\/g' | paste -sd'|' -)

cat <<JSON
{
  "\$schema": "https://json-schema.org/draft/2020-12/schema",
  "\$id": "https://thruput.se/agents/schemas/declared-ids.g.schema.json",
  "title": "Declared ids",
  "description": "Generated by scripts/declared-ids.schema.sh from every id declared in governance/: the governance schema with the Id and References dynamic anchors bound to their enumeration",
  "examples": [
    {
      "axioms": []
    }
  ],
  "\$ref": "https://thruput.se/agents/schemas/governance.schema.json",
  "\$defs": {
    "Id": {
      "\$dynamicAnchor": "Id",
      "enum": [$enumeration]
    },
    "References": {
      "\$dynamicAnchor": "References",
      "pattern": "^[^\\\\[]*(?:(?:\\\\[\\\\[(?:$alternation)\\\\]\\\\]|\\\\[[^\\\\[])[^\\\\[]*)*\\\\[?\$"
    }
  }
}
JSON
