name: CI Check

on:
  push:
    branches:
      - main
      - yaml-governance-documents
  pull_request:
    branches:
      - main
      - yaml-governance-documents

permissions:
  contents: read

jobs:
  validate:
    name: Validate Documents Against Schemas
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install the JSON Schema CLI
        uses: sourcemeta/jsonschema@v17.0.0

      - name: Validate documents
        run: scripts/validate.sh

